### ISSUE TITLE
frontend wont start , error "sh: vue-cli-service: not found"

### ISSUE THREAD

**Issue by avico78** [dwisulfahnur/blog-fastapi-vuejs#25]
frontend wont startup ,
throw error:
 ```
frontend_1 | > vue-cli-service serve

frontend_1 |

frontend_1 | sh: vue-cli-service: not found

```

Manage to fix inspiring this post:
https://github.com/vuejs/vue-cli/issues/3506#issuecomment-466915042

Dockerfile is correct so only left is adding exposing node_modules in docker-compose

```
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/home/app/frontend
      - /home/app/frontend/node_modules
    depends_on:
      - backend
    ports:
      - "8080:8080"
```
